http://localhost:3100/users

###
http://localhost:3100/users/1

###
http://localhost:3100/posts

###
http://localhost:3100/posts/1
NP-Demo: Best Class Ever

###
POST http://localhost:3100/posts 
Content-Type: application/json

{
  "src": "https://apod.nasa.gov/apod/image/2111/MilkyWayWaterfall_XieJie_960.jpg",
  "title" : "A Waterfall and the Milky Way",
  "caption" : "A Waterfall and the Milky Way",
  "user_handle": "@JewPaltz",
  "isPublic": true
}

###
https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY